import './globals.css';
import type { Metadata } from 'next';
import React from 'react';
import Navbar from './components/Navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <header className="flex px-4 py-5 bg-primary-light">
          <Navbar/>
        </header>
        {children}
        <footer className=" flex items-center px-8 py-7 gap-4 w-screen mt-auto">
          <div className="w-full max-w-7xl flex flex-col gap-3 md:flex-row justify-between items-center mx-auto">
            <h2 className="font-bold text-xl text-font">Manager</h2>
            <p className="text-gray-600 text-center text-font">
              Where you can manage all stuff. From tasks to money.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
